"""Static data for NaviX — Bengaluru pilot."""

ZONES = [
    'Indiranagar','Whitefield','Koramangala','HSR Layout','BTM Layout',
    'Jayanagar','JP Nagar','Banashankari','Rajajinagar','Malleshwaram',
    'Hebbal','Yeshwanthpur','Marathahalli','Bellandur','Sarjapur',
    'Electronic City','Bommanahalli','Begur','Yelahanka','Hennur',
    'Frazer Town','MG Road','Brigade Road','Cubbon Park','Vidhana Soudha',
    'Cunningham Road','Domlur','CV Raman Nagar','Old Airport Rd','ITPL',
    'KR Puram','Mahadevapura','Brookefield','Kadugodi','Hoodi',
    'Ramamurthy Nagar','TC Palya'
]

SEGMENTS = [
    (1,'Indiranagar','Domlur',2.1,4),(2,'Indiranagar','CV Raman Nagar',1.8,2),
    (3,'Domlur','Old Airport Rd',1.5,4),(4,'Old Airport Rd','Marathahalli',4.2,6),
    (5,'Marathahalli','Bellandur',3.6,4),(6,'Bellandur','Sarjapur',5.1,4),
    (7,'Sarjapur','HSR Layout',4.0,4),(8,'HSR Layout','BTM Layout',2.8,4),
    (9,'BTM Layout','JP Nagar',3.2,4),(10,'JP Nagar','Banashankari',2.5,4),
    (11,'Banashankari','Jayanagar',3.0,4),(12,'Jayanagar','Koramangala',4.5,4),
    (13,'Koramangala','BTM Layout',2.2,4),(14,'Koramangala','HSR Layout',3.5,4),
    (15,'Koramangala','Indiranagar',4.8,4),(16,'MG Road','Brigade Road',0.8,2),
    (17,'MG Road','Cubbon Park',1.2,4),(18,'Cubbon Park','Vidhana Soudha',1.0,4),
    (19,'Vidhana Soudha','Cunningham Road',1.5,4),(20,'Cunningham Road','Frazer Town',2.0,4),
    (21,'Frazer Town','Hebbal',5.5,6),(22,'Hebbal','Yelahanka',6.2,6),
    (23,'Yelahanka','Hennur',4.8,4),(24,'Hennur','Ramamurthy Nagar',3.2,4),
    (25,'Ramamurthy Nagar','KR Puram',2.5,4),(26,'KR Puram','Mahadevapura',3.0,4),
    (27,'Mahadevapura','Whitefield',4.5,6),(28,'Whitefield','ITPL',1.5,6),
    (29,'ITPL','Kadugodi',2.8,4),(30,'Kadugodi','Hoodi',3.5,4),
    (31,'Hoodi','Brookefield',2.0,4),(32,'Brookefield','Marathahalli',3.8,4),
    (33,'Marathahalli','Whitefield',6.5,6),(34,'Electronic City','Bommanahalli',4.0,6),
    (35,'Bommanahalli','BTM Layout',3.5,4),(36,'Bommanahalli','Begur',2.8,4),
    (37,'Begur','Electronic City',3.0,4),(38,'Rajajinagar','Malleshwaram',2.5,4),
    (39,'Malleshwaram','Yeshwanthpur',3.2,4),(40,'Yeshwanthpur','Hebbal',4.5,6),
    (41,'Rajajinagar','Cubbon Park',5.0,4),(42,'Yeshwanthpur','Rajajinagar',2.8,4),
    (43,'Indiranagar','MG Road',5.2,4),(44,'MG Road','Frazer Town',3.5,4),
    (45,'BTM Layout','Bommanahalli',3.5,4),(46,'Hennur','Frazer Town',4.0,4),
    (47,'CV Raman Nagar','KR Puram',5.0,4),(48,'Domlur','Koramangala',3.0,4),
    (49,'JP Nagar','BTM Layout',2.5,4),(50,'Banashankari','JP Nagar',2.0,4),
    (51,'TC Palya','KR Puram',2.0,2),(52,'TC Palya','Ramamurthy Nagar',2.5,2),
    (53,'Hoodi','Mahadevapura',2.2,4),(54,'Brookefield','Whitefield',3.5,4),
    (55,'Bellandur','HSR Layout',4.5,4),(56,'Sarjapur','Bellandur',3.8,4),
    (57,'Electronic City','HSR Layout',8.5,6),(58,'Yelahanka','Hebbal',5.0,6),
    (59,'Mahadevapura','Marathahalli',3.2,4),(60,'KR Puram','Indiranagar',6.5,4),
    (61,'Hennur','Hebbal',5.5,4),(62,'Brigade Road','Cunningham Road',1.8,4),
    (63,'Cubbon Park','Brigade Road',0.9,4),(64,'Frazer Town','CV Raman Nagar',3.0,4),
    (65,'Domlur','MG Road',3.5,4),(66,'Whitefield','Hoodi',2.5,4),
    (67,'Kadugodi','Whitefield',3.0,4),(68,'ITPL','Brookefield',2.0,4),
    (69,'Yeshwanthpur','Cubbon Park',5.5,4),(70,'Malleshwaram','Cubbon Park',4.0,4),
    (71,'Hebbal','Cunningham Road',6.0,6),(72,'Begur','BTM Layout',4.0,4),
    (73,'Electronic City','Begur',2.5,4),(74,'Old Airport Rd','Indiranagar',2.8,4),
    (75,'Marathahalli','Old Airport Rd',4.0,6),(76,'CV Raman Nagar','Domlur',2.5,4),
]

SIGNALS = [
    {'id':1,'name':'Trinity Circle','zone':'MG Road','cycle_time':120},
    {'id':2,'name':'Domlur Flyover','zone':'Domlur','cycle_time':110},
    {'id':3,'name':'Marathahalli Bridge','zone':'Marathahalli','cycle_time':130},
    {'id':4,'name':'Silk Board','zone':'BTM Layout','cycle_time':150},
    {'id':5,'name':'Hebbal Flyover','zone':'Hebbal','cycle_time':140},
    {'id':6,'name':'KR Puram Junction','zone':'KR Puram','cycle_time':120},
    {'id':7,'name':'Tin Factory','zone':'CV Raman Nagar','cycle_time':110},
    {'id':8,'name':'Whitefield Junction','zone':'Whitefield','cycle_time':125},
    {'id':9,'name':'Sarjapur Junction','zone':'Sarjapur','cycle_time':115},
    {'id':10,'name':'Bellandur Signal','zone':'Bellandur','cycle_time':120},
    {'id':11,'name':'Koramangala 6th Block','zone':'Koramangala','cycle_time':100},
    {'id':12,'name':'Madiwala','zone':'BTM Layout','cycle_time':130},
    {'id':13,'name':'Banashankari Circle','zone':'Banashankari','cycle_time':110},
    {'id':14,'name':'Jayanagar 4th Block','zone':'Jayanagar','cycle_time':105},
    {'id':15,'name':'Yeshwanthpur Junction','zone':'Yeshwanthpur','cycle_time':115},
    {'id':16,'name':'Electronic City Toll','zone':'Electronic City','cycle_time':135},
    {'id':17,'name':'Cubbon Park West','zone':'Cubbon Park','cycle_time':100},
    {'id':18,'name':'ITPL Main Gate','zone':'ITPL','cycle_time':110},
]

INCIDENTS = [
    {'id':1,'type':'Accident','location':'Marathahalli Bridge','severity':'high','reported_at':'08:42 AM','status':'active'},
    {'id':2,'type':'Roadwork','location':'Old Airport Rd','severity':'medium','reported_at':'07:15 AM','status':'active'},
    {'id':3,'type':'Waterlogging','location':'Silk Board','severity':'high','reported_at':'08:55 AM','status':'active'},
    {'id':4,'type':'Signal failure','location':'KR Puram','severity':'medium','reported_at':'09:10 AM','status':'active'},
    {'id':5,'type':'Vehicle breakdown','location':'Hebbal Flyover','severity':'low','reported_at':'08:30 AM','status':'resolved'},
]
